# -*- coding: utf-8 -*-
"""app_inference.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15twpTQOQ5jUi6qwF0mggWdW-19PcXoYt
"""

import os
import json
import joblib
import pandas as pd

MODEL_PATH = "fifa_pipeline_model.joblib"
META_PATH = "metadata.json"

pipeline = joblib.load(MODEL_PATH)

with open(META_PATH, "r") as f:
    meta = json.load(f)

csv_name = meta["data_csv_used"]
df = pd.read_csv(csv_name)

target_col = meta["target_col"]

if target_col in df.columns:
    X = df.drop(columns=[target_col])
else:
    X = df.copy()

sample = X.iloc[[0]].copy()
prediction = pipeline.predict(sample)

print("Sample Input:")
print(sample.head(1))
print("\nModel Prediction:")
print(prediction[0])